# Generated by Django 4.0.6 on 2022-07-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Name of the Bank')),
                ('rate', models.FloatField(verbose_name='Mortgage Rate')),
                ('payment', models.IntegerField(verbose_name='Payment')),
            ],
        ),
    ]
